MusicPlayerDaemon/website

content/clients/index.md
Created a Web Clients group and added my own project to this group.
=> Added http://www.netjukebox.nl/

content/clients/index.md
Sonata is now maintained mostly on github (nongnu site seems to be abandoned)
=> Add sonata to list

content/clients/index.md
Added the MPDroid Android client to the list.
=> Added MPDroid

content/clients/index.md
I regularly use this client so I thought I would add it to the list. 
[https://github.com/boysetsfrog/vimpc](https://github.com/boysetsfrog/vimpc)
=> Client: vimpc

content/clients/index.md
This adds a new web client and fixes a tiny typo in the previous one.
=> Added the 'cyp' web client

content/clients/index.md
Added some more mpd clients to list under Graphical Clients category. Added dummy description to Android Clients. Resorted Graphical and Android clients list.
=> Added some more mpd clients

content/libs/python-mpd2.md, content/libs/python-musicpd.md
=> Update and fix broken broken links

content/clients/index.md
Add the FLOSS utility client MPD_sima : https://kaliko.me/mpd-sima/
=> clients: Add MPD_sima non interactive utility client

content/clients/index.md
=> Reintroduce Non-interactive Clients

content/clients/index.md
I'd like to add my MPD client to the list. https://github.com/SoongNoonien/mpdevil
=> Client: mpdevil

content/clients/index.md, content/libs/index.md
Hi,
I'd like to add my MPD client for Wear OS to the list.
=> Add MPD Client for Wear OS and client library.

content/clients/index.md
https://github.com/CDrummond/cantata
NOTE Cantata is now in a bug-fix only state. Therefore, new features are unlikly to be implemented unless pull requests are submitted. The current release, 2.4.x, is likely to be the last feature release.
=> Cantata moved to Unmaintained Clients

content/clients/index.md
=> Add mmtc to the clients list

content/clients/index.md
=> Add mpd-ynca client

content/clients/index.md
I've been using it for over three years, so someone else might be able to as well.
=> Add nncmpp to the list of clients

content/posts/2021-02-19-ymuse-0-16-released.md
Add a news about Ymuse release. I'm not sure if this is appropriate for MPD's newsfeed (but I'd love to see it there!)
=> ymuse release v0.16

content/posts/2021-11-25-ymuse-0-18-released.md
Add news about the latest Ymuse release
=> ymuse release v0.18

content/clients/index.md, content/posts/2022-09-18-stylophone-2-5-released.md
👋 Stylophone is now available for iOS, so I've updated the clients page to match.  
I also added in a news article for it since I saw other clients do the same -- Hopefully it's ok!
=> Update Stylophone info

content/clients/index.md
Best music parts tracker for MPD
=> Add link to new `bmp` utility client

content/clients/index.md
https://github.com/Nyx0uf/Shinobu
=> Add iOS client Shinobu

content/libs/index.md
This PR adds MphpD to the list of client libraries.
=> Add MphpD to list of client libraries

content/commercial.md
A myMPD user notified me about this: https://github.com/jcorporation/myMPD/discussions/1140
=> Add "IDEON audio eos Stream" commercial product

content/clients/index.md
If you wish, please add my little client to your list. 
Thanks!  dr.gerg@drgerg.com
=> Add MMC4W to list.

content/clients/index.md
Add a link to the Retrotube project (https://gitlab.com/eric.yape/retrotube)
=> Update "Web Clients" sections with Retrotube

content/posts/2024-02-24-mmc4w-v2-0-0-released.md
This process has been really helpful.  Here is the post announcing version 2.0.0 of MMC4W.
Thanks!
=> Post MMC4W v2.0.0 released

content/posts/2024-03-01-mmc4w-v2-0-1-released.md
MMC4W The Minimal MPD Client for Windows [v2.0.1](https://github.com/drgerg/mmc4w/tree/main) is now available.
A new Queue menu lists the queue so you can search for and jump to specific songs in the current queue.
Folder art is now supported in addition to embedded art.
=> MMC4W v2.0.1 Released

content/posts/2024-04-13-python-musicpd-0.9.0-released.md
python-musicpd released announcement.
=> python-musicpd 0.9.0 released

content/clients/index.md
Hi, I'm the author of [MPC Bar](https://github.com/spnw/mpc-bar). I've been using it for the better part of a year (as probably the only user...) and I think it's stable and useful enough to be on the official list.
=> Add MPC Bar to client list

content/libs/index.md
Added my C# client library to the list
=> Added a C# library to the list
